[phases.setup]
nixPkgs = ["nodejs_20", "chromium", "nss", "atk", "cups", "pango", "cairo", "glib", "dbus", "fontconfig", "alsa-lib", "xorg.libX11", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXfixes", "xorg.libXrandr", "xorg.libxcb", "mesa", "libgbm"]

[phases.install]
cmds = ["npm ci"]

[start]
cmd = "node index.js"
